spring:
  application:
    name: graphql-api
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bookdb
    hikari:
      poolName: Hikari
      auto-commit: false
  graphql:
    graphiql:
      enabled: true